# global values
global:
  env: 
    "ASPNETCORE_ENVIRONMENT": "Staging"
    "ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"

test-app-cli:

  image:
    repository: 172.23.64.152:5000/my-test-cli
    pullPolicy: IfNotPresent
    tag: ""

  job:
    ## Should the job be rescheduled on the same node if it fails, or just stopped
    restartPolicy: Never

test-app-cli-exec-host:

  image:
    repository: 172.23.64.152:5000/my-test-cli-exec-host
    pullPolicy: IfNotPresent
    tag: ""

  serviceAccount:
    create: false

test-app-api:

  replicaCount: 1

  env: 
    "ASPNETCORE_ENVIRONMENT": "Development"

  image:
    repository: 172.23.64.152:5000/my-test-api
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/"
    hosts:
      - host: "chart-example.local"
        paths: 
        - "/my-test-app"

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

test-app-service:

  replicaCount: 1

  image:
    repository: 172.23.64.152:5000/my-test-service
    pullPolicy: IfNotPresent
    tag: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false